name: Build, Test, and Deploy Java Spring Boot Application

on:
 pull_request:
    branches: [ "master" ]

jobs:
  setup_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle   
        run: ./gradlew test 

  docker_build_and_push:
    needs: setup_and_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker
        run: |
          sudo systemctl start docker
          docker --version

      - name: Build new image
        run: docker build -t devops-menu-project .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u Jonathanh162 --password-stdin

      - name: Tag and Push Docker Image
        run: |
          docker tag devops-menu-project ghcr.io/jonathanh162/devops-menu-project:latest 
          docker push ghcr.io/jonathanh162/devops-menu-project:latest

  fake_deploy:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Deploying image: ghcr.io/jonathanh162/devops-menu-project:latest to test environment"'
