name: Build and Test Java Spring Boot Application

on:
  push:
    branches: [ "master", "Development_Branch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

  # Build and test with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle   
        run: ./gradlew test 

      - name: Build new image
        run: docker build -t devops-menu-project .
