name: Build and Test Java Spring Boot Application

on:
  push:
    branches: [ "master", "Development_Branch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

  # Build and test with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle   
        run: ./gradlew test 

      - name: Setup Docker
        run: |
          sudo systemctl start docker
          docker --version

      - name: Build new image
        run: docker build -t devops-menu-project .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u Jonathanh162 --password-stdin

      - name: Tag and Push Docker Image
        run: |
         docker tag devops-menu-project ghcr.io/jonathanh162/devops-menu-project:latest 
         docker push ghcr.io/jonathanh162/devops-menu-project:latest

      - name: Fake Deploy to Test Environment
        run: 'echo "Deploying image: ghcr.io/jonathanh162/devops-menu-project:latest to test environment"'

